### PR TITLE
⚡️ Boosting Performance: React.js Code Optimizations

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
This pull request introduces several minor performance improvements for the React.js code in the Raspberry Pi Foundation Code Editor. The following changes have been made:

1. Made `useMemo` dependency more specific: Changed the dependency from `params` to `params["width-larger-than-880"]`. This change offers the following advantage:
   - By making the `useMemo` dependency more precise, unnecessary re-evaluations are avoided when other properties of `params` change. This can improve the performance by reducing unnecessary computations.

2. Made `useEffect` dependency more precise: Updated the dependency to include only the specific value used inside the function body. This change provides the following advantage:
   - By specifying a more precise dependency, the `useEffect` hook will only be triggered when the specific value it depends on changes. This can prevent unnecessary re-rendering and improve performance.

3. Implemented React.js concurrency with `startTransition`: Utilized React.js concurrency features, specifically `startTransition`, to achieve a more responsive user interface. This change offers the following advantage:
   - By using `startTransition`, the code can prioritize rendering high-priority updates, improving the perceived responsiveness of the UI. This can result in a smoother user experience.

4. Utilized `React.lazy` for lazy loading routes and prefetching using Webpack prefetch comment: Introduced `React.lazy` to lazily load routes and prefetch them using Webpack prefetch comment. This change provides the following advantage:
   - Lazy loading routes can improve the initial loading time of the application by deferring the loading of non-essential components until they are actually needed. Prefetching these routes using Webpack prefetch comment can further enhance performance by proactively fetching the required resources in the background.

Please review the changes and provide any suggestions or feedback for the Suspense fallback, which is currently set as an empty fragment.

Apologies for any mistakes made. Feel free to provide any additional suggestions or improvements for the PR.

### CODE REVIEW

**Comment by loiswells97** [comment]
Thanks for your contribution! I've merged your changes into a new `boosting-performance` branch and created a [PR](https://github.com/RaspberryPiFoundation/editor-ui/pull/686) so we can run our automated tests and review your changes.

**Comment by sanjaiyan-dev** [comment]
> Thanks for your contribution! I've merged your changes into a new `boosting-performance` branch and created a [PR](https://github.com/RaspberryPiFoundation/editor-ui/pull/686) so we can run our automated tests and review your changes.

Okay 🫱🏼‍🫲🏾✨

**Comment by loiswells97** [comment]
I've added a few review comments on the [new PR](https://github.com/RaspberryPiFoundation/editor-ui/pull/686). There are a few tests failing as well but it might be related to the comments I've already made on the code changes. Thanks again @sanjaiyan-dev for your work on this!

**Comment by sanjaiyan-dev** [comment]
> I've added a few review comments on the [new PR](https://github.com/RaspberryPiFoundation/editor-ui/pull/686). There are a few tests failing as well but it might be related to the comments I've already made on the code changes. Thanks again @sanjaiyan-dev for your work on this!

You're welcome !

**Pull request merged**
